name: Run Portfolio Tracker

on:
  workflow_dispatch:  # manual start
  schedule:
    - cron: '0 */6 * * *'  # auto re-start ever 6 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          RPC_URL: ${{ secrets.RPC_URL }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          COINGECKO_ID: ${{ secrets.COINGECKO_ID }}
        run: python main.py
